; ALLOWS ONE TO START THE APPLICATION WITH RUN
; SYS 2064
*=$0801 
         BYTE $0C, $8, $0A, $00, $9E, $20, $32, $30, $36, $34, $00, $00, $00, $00, $00

; ADDRESSES WHERE CERTAIN SID SUBROUTINES ARE FOUND.
; ONE MIGHT LOAD THESE FROM THE SID FILE TOO, BUT IN THE SAKE OF AN EXAMPLE, 
; THESE ARE HARD CODED HERE.
LOAD_ADDR       = $1000 ; LOAD ADDRESS, DEPENDS ON THE SID DATA
INIT_ADDR       = $13C8 ; INIT ADDRESS, DEPENDS ON THE SID DATA
PLAY_ADDR       = $875B ; PLAY ADDRESS, DEPENDS ON THE SID DATA

INIT    JSR INIT_ADDR 
PLAY    JSR PLAY_ADDR 

WAIT    LDA $D012 ; WAIT FOR RASTER LINE 250, AND THEN CALL PLAY SUBROUTINE AGAIN. TODO: USE INTERRUPTS
        CMP #250
        BNE WAIT
        BEQ PLAY

* = LOAD_ADDR
incbin "Boulder_Dash.sid",$7E   ; LOAD SID FILE DATA. DATA STARTS AT '7C' BYTES AFTER THE HEADER.
                                ; BUT WE ALSO NEED TO SKIP THE PART OF THE DATA WHICH
                                ; INDICATES THE LOAD ADDRESS, SO WE SKIP '7E' BYTES.